### ISSUE TITLE
Add dependabot to keep actions up to date

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/plugin-actions#7]
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#example-dependabotyml-file-for-github-actions

`interval: "monthly"`

should be enough

**Comment by tolzhabayev** [comment]
fyi @academo

**Comment by academo** [comment]
@tolzhabayev it seems that this is to keep actions you have in your repository (inside `.github/workflows`) and it doesn't work with actions themselves like this one.

**Comment by tolzhabayev** [comment]
argh right, ignore it then
